import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const NAMES = [
"ABAETE","ACARAI","ADAMATTI","AGUAS CLARAS","AIMORE","ALAMO","ALE","ALEXANDRE","ALINE",
"ALPES","AMERICA PALACE","ANA CAPRI","ANA CAPRI ALT","ANAPOLIS","ANCORA","ANDERSON",
"ANDORINHA","ANDRE PUGEN","ANDREALINE","ANGRA DOS REIS","ANTHURIUM","ANTIGUA","AQUARIUS",
"ARCO IRIS","ARTICO","ATHENAS","ATLANTIDA","BARBARA","BEACH SKY","BELA VISTA","BELLAGIO",
"BENAMI","BIBIANE","BIER","BONANZA","BRASIL","BRAVO","BRILHO DAS ONDAS","BROGNI",
"BUENOS AIRES","BUZIOS","CACIQUE","CAETANO FUGINITI","CALIFORNIA","CAMBAS","CANDEIAS",
"CÂNDIDO","CAPRI","CARAIBAS","CARAVELA","CARIBE","CASTELOON PARK","CÉLIO MARQUES FERNANDES",
"CENTROMAR","CHAPTER 28","CHARRUA","CINARA","COLUMBIA","CONDADO DE FLORENÇA",
"CONDADO DE SANTIAGO","CONFORTO","COPACABANA","CORALINO","CORINTHO","CORRIENTES",
"CORTE REAL","COSTA AZUL","COSTA DO SOL","COSTANERA","CRISTAL AZUL","DAIMAR","DANI",
"DELPHUS","DENIZE","DESIRE","DHIOGOS","DI TRENTO","DIANA","DIANE","DISNEYMAR",
"DOM ARTHUR","DOM BORGES","DOM CELIBERTO","DOM MANOEL","DOM MATHEUS","DOM RAMIRO",
"DOM RAPHAEL","DOMENICO","DOM FRANCESCO","DONA ANGELICA","DONA CECILIA","DONA DALILA",
"DONA EMILIA","DONA FRANCISCA","DONA ILDA","DONA JESSY","DONA LAURA","DORAL","DOUTEL",
"DREGER","DUANI","DUAR","EDUARDO","ÉFESO","EGEU","EL GREGO","ELEANDRA","EMBAIXADOR",
"ENTRE RIOS","ESMERALDA","ESPLANADA DO FAROL","ESTEVES","ESTEVES DO FAROL","EVEREST",
"FAROL","FLORENCA","FORTELES","FOUR SEASONS","FRATELLI","GABRIELA","GISELE PALACE",
"GOLDEN STAR","GREEN GARDEN","GUARACY PALACE","HENRIQUE","HENRIQUE SIRTOLI","IBERE",
"ILE DE LA CITE","ILHA DE ITAPARICA","ILHA DE SANTURINE","ILHA DO MAR","ILHA DO MEL",
"ILHA DOS CORAIS","ILHA PORCHAT","ILHA ROSADA","ILHA VERDE","ILHAS CANÁRIAS",
"ILHAS CAYMAN","IMPERADOR","IMPERIAL","IPANEMA","IRMÃOS CALEFI","ITAPEMA",
"JAIR MARTINELLO","JANE PISANE","JANICE","JARDIM MEDITERRANEO","JARDINS DE IRACEMA",
"JOÃO ALVES DINIZ","JORGE MARTELETE","JOSÉ PÉS","JULINE","JULIO FERNANDES","JURUBA",
"KATRINE","KAULANA PARK","KIELING","KLIEN","LADY DY","LAJEADO","LARISSA","LAUREANT",
"LB","LE CASTELLA","LE CLASSIC","LE GRAND PARC","LE PARC","LIDIANI","LIFE PROMENADE",
"LISIE","LIVIA","LOPES","LOS ANGELES","LUAR","LUIZ BASSANI","LYNEMAR BUSINESS",
"MACARAJA","MAIARA MARTINELLO","MAISON ROSE","MAISON SCHIA","MANI",
"MANOEL FERNANDES","MANOEL FERNANDES DA SILVEIRA","MARACAJA","MARTINELLO","MENA BARRETO",
"MICHELI","MILLENIUM","MILTON LUCAS","MIRADOR ACONCÁGUA","MIRANTE DA LAGOA",
"MIRANTE DA SEPE","MIRANTE DA SERRA","MIRANTE DO SOL","MISSIONES","MONTE CARLO",
"MONTE NEGRO","MORADA DA ANCORA","MORADA DA PRAÇA","MORADA DA PRAIA","MORADA DAS DUNAS",
"MORADA DAS HORTENCIAS","MORADA DAS ONDAS","MORADA DO MAR","MORADA DO SOL","MUNIZ",
"MYKONOS","NENA","NILMAR","NONOAI","NOTARIUM","OLYMPHOS","OTACILIO DA COSTA",
"OTAVIO MARTINELLO","OURO PRETO","PALADIUM","PALAZZO BELLA VITA","PALAZZO FELICITA",
"PANDOLFI PASSOS","PARATI","PARIS PALACE","PARQUE HUMAITA","PASSEIO DO MAR",
"PENA BRANCA","PERI","PERINI WORK CENTER","PEROLA","PEROLA DO MAR","PIDORAMA",
"PIRAMIDE","PISANI","PORT BEACH","PORT VELL","PORTINARI","PORTO DE PALOS",
"PORTO PRINCIPE","PORTO SEGURO","PORTO SOL","POTY","PRAIA DE ARMAÇÃO","PRAIA DE BELAS",
"PREMIUM","PRIME SQUARE","PUERTO VANUS","PUSTI","QATAR","RANNA","RASAN","RAVENA",
"REGGIANE","RIALI","RIO DOS SINOS","RIO GUAÍBA","RIO HEVER","RIO NILO","RIO PESCARA",
"RIO RENO","RIO TOPÁZIO","RIO VOLGA","RODIELIS","ROYAL PALACE","RUDA","SAMIRA",
"SAN CARLOS","SAN CIRO","SAN FRANCISCO","SAN ISIDORO","SAN MARINE","SAN MARTIN",
"SAN PIETRO","SANS SOUCI","SANTO ANTONIO","SÃO CARLOS","SÃO CONRADO","SCHERER",
"SCHWARTZ ELEGANCE","SCHWATZ","SCUREDO","SEIVAL","SEPE","SHALON","SHOPPING LYNEMAR",
"SIMINOVICH","SION","SOFIA","SOLAR BARRERA","SOLAR DA PRACA","SOLAR DA PRAIA",
"SOLAR DAS ALAMANDAS","SOLAR DOS FREITAS","SOLAR MARTINS","SOLAR ZACOUTEGUY",
"SOLARIS POTI","SUBLIME","SUNSET BOULEVARD","TAIPEI","TARSILA DO AMARAL","TESSARO",
"THALIA","TIAGO","TISCHLER","TOMAZ","TONHO RESIDENCE","TRINIDA","TUPA","TUPANCI",
"ULISSES","VELEIOS","VERDE MAR","VIA APIA","VID HOME & CLUB","VILA NOBRE",
"VILLA CADIZ","VILLA MARBELLA","VINA DEL MAR","VIRGINIA","VITORIA REGIA",
"VIVENDAS DO ATLANTICO","VIVIANE","WALDIR REIS","XAVANTES","ZANOTTO","ZEUS","ZURICH",
"ZANOTTO","ZEUS","ZURICH",
];

async function main() {
  // Get first profile to use as userId, or create a system one
  let profile = await prisma.profile.findFirst();
  if (!profile) {
    profile = await prisma.profile.create({
      data: { id: 'sistema', email: 'sistema@viva.com', name: 'Sistema' },
    });
    console.log('Created system profile');
  }

  const userId = profile.id;
  let count = 0;

  for (const name of NAMES) {
    const existing = await prisma.building.findFirst({ where: { name, userId } });
    if (!existing) {
      await prisma.building.create({
        data: {
          name,
          neighborhood: 'Centro',
          city: 'Capão da Canoa',
          state: 'RS',
          userId,
        },
      });
      count++;
    }
  }

  console.log(`Inserted ${count} buildings (skipped ${NAMES.length - count} duplicates)`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
